#!/usr/bin/env ruby

require 'rubygems'
require 'rot'

mappings = {
  '0' => '1',
  '1' => '0',
  '2' => '0',
  '3' => '0',
  '4' => '1',
  '5' => '0',
  '6' => '1',
  '7' => '0',
  '8' => '2',
  '9' => '1'
}

rot = Rot.new mappings, '?', /./, /./
puts rot.decrypt(STDIN.read).scan(/./).inject(0) { |sum, char| sum += char.to_i; sum }
