#!/usr/bin/env ruby

# Dont filter, simply highlight a given keyworkd from stdin.
# Usage: $ cat log/development.log | hls completed

abort 'No pattern given' if ARGV[0].nil?

trap('SIGINT') { }

$stdout.sync = true

STDIN.each do |line|
  puts line.gsub(/(#{ARGV[0]})/i) { |x| "[0;31;1m#{$1}[0m" }
end

